### ISSUE TITLE
Binding tool releases should provide an  bt-arm64-apple-darwin flavor

### ISSUE THREAD

**Issue by anthonydahanne** [dmikusa/binding-tool#39]
It seems like the strategy used here to generate multiple binaries for multiple platforms is to rely on the OS default toolchain:

```
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
```

Unfortunately, this approach is limited by the number of OSes/ platform supported by the default provided runners by GH.

We could envision adding self hosted runner, but for a single project, that seems overkill.

I believe the long term solution is to rely on on rust `toolchains` https://rust-lang.github.io/rustup/cross-compilation.html
